export default interface PaymentRequestData {
    title?: string;
    type?: string;
    merchantAccount: string;
    reference: string;
    currency: string;
    thumbnail?: string;
    description?: string;
    url?: string;
    droppSignature?: string;
    failureURL?: string;
    successURL?: string;
    successMessage?: string;
    amount?: number;
    lowerLimit?: number;
    upperLimit?: number;
    maxAmount?: number;
    fixAmount?: number;
    start?: Date | null;
    expiry?: Date | null;
    frequency?: string;
    status?: string;
    country?: string;
    purchaseExpiration?: number;
    referralFee?: number;
    referrer?: string;
    distribution?: string;
    purchaseURL?: string;
    shareURL?: string;
    confirmURL?: string;
    cancelURL?: string;
    qrCode?: boolean;
    buyerName?: string;
    buyerEmail?: string;
    buyerPhone?: string;
    payByCC?: boolean;
    payByBank?: boolean;
    infoAccess?: boolean;
    siteUrl?: string;
    invoiceId?: string;
    b2bInvoice?: boolean;
    uuid?: string;
    uuid_type?: string;
    tax?: number;
    tip?: number;
    acceptPaymentDelay?: boolean;
    noOffers?: boolean;
    submitToCallBack?: 'GET' | 'POST';
}
